name: feniqs
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - yaml
  - pyyaml
  - meshio
  - fenics
  - gmsh
  - python-gmsh
  - pip
  - pip:
      - "--editable=git+https://github.com/BAMresearch/FEniQS.git@main#egg=feniQS"
