name: feniqs
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - seaborn
  - yaml
  - pyyaml
  - fenics
  - meshio
  - gmsh >= 4.11
  - python-gmsh
  - pip
  - pip:
      - -e .
